---
application:
  name: "puppala-koushik"
  project: "koushik puppala"
  organization: "QoveryCommunity"
routers:
- name: main-puppala-koushik
  custom_domains:
  - branch: puppala-koushik
    domain: koushikpuppala.live
  routes:
  - application_name: puppala-koushik
    paths:
    - /
