---
application:
  name: "puppala-koushik"
  project: "testing"
  organization: "QoveryCommunity"
routers:
- name: "main-puppala-koushik"
  routes:
  - application_name: "puppala-koushik"
    paths:
    - "/*"
