---
application:
  name: "koushikpuppala"
  project: "Koushik Puppala"
  organization: "QoveryCommunity"
routers:
- name: "main-koushikpuppala"
  routes:
  - application_name: "koushikpuppala"
    paths:
    - "/*"
