---
application:
  name: "koushikpuppala"
  project: "Koushikpuppala"
  publicly_accessible: true
  port: 8080
  organization: "QoveryCommunity"
routers:
- name: "main-koushikpuppala"
  custom_domains:
  - branch: Koushikpuppala
    domain: koushikpuppala.live
  routes:
  - application_name: "koushikpuppala"
    paths:
    - "/*"
