name: Puppala Koushik

on:
  push:
    branches: [ Puppala-Koushik ]
  pull_request:
    branches: [ Puppala-Koushik ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag Puppala-Koushik:$(date +%s)
